[package]
  cjc-version = "1.1.0"
  name = "markdown"
  organization = ""
  description = "Versioned, bounded, extensible Markdown parser and renderer for Cangjie"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "static"
  compile-option = "-O2"
  override-compile-option = ""
  link-option = "-L target/native -lmarkdown_scanner"
  package-configuration = {}

[dependencies]
