#!/usr/bin/env python3
"""Validate and render the single release-evidence source of truth."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "release-evidence.json"
README = ROOT / "README.md"
BENCHMARK_REPORT = ROOT / "docs/reports/benchmark.md"
ACCEPTANCE = ROOT / ".agent/acceptance-report.md"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load() -> dict[str, object]:
    return json.loads(EVIDENCE.read_text(encoding="utf-8"))


def benchmark_markdown(data: dict[str, object]) -> str:
    benchmark = data["benchmark"]
    assert isinstance(benchmark, dict)
    ratios_pass = (
        benchmark["commonmarkRatio"] <= benchmark["ratioLimit"]
        and benchmark["gfmRatio"] <= benchmark["ratioLimit"]
    )
    status = "PASS" if benchmark["status"] == "current" and ratios_pass else "FAIL"
    return f"""# Release benchmark report

Status: **{status}**

Evidence status: `{benchmark['status']}`. {benchmark['note']}

- CommonMark parse-only geometric mean ratio vs cmark: `{benchmark['commonmarkRatio']:.2f}x` (limit `{benchmark['ratioLimit']}x`).
- GFM parse+HTML geometric mean ratio vs cmark-gfm: `{benchmark['gfmRatio']:.2f}x` (limit `{benchmark['ratioLimit']}x`).
- Raw report: `{benchmark['rawPath']}`.
- Raw SHA-256: `{benchmark['rawSha256']}`.
- Tested source commit: `{benchmark['sourceCommit'] or 'UNBOUND'}`.
- Benchmark Cangjie SDK: `{benchmark['sdkVersion'] or 'UNBOUND'}`.
- Product source archive SHA-256: `{benchmark['productSourceArchiveSha256']}`.
- Benchmark harness SHA-256: `{benchmark['benchmarkHarnessSha256']}`.
- markdown driver SHA-256: `{benchmark['markdownDriverSha256']}`.
- cmark driver SHA-256: `{benchmark['cmarkDriverSha256']}`.
- cmark-gfm driver SHA-256: `{benchmark['cmarkGfmDriverSha256']}`.
- cmark: `{benchmark['cmark']}`.
- cmark-gfm: `{benchmark['cmarkGfm']}`.

This file is generated by `python3 scripts/release_evidence.py --write` from
`release-evidence.json`; do not edit benchmark numbers here.
"""


def readme_block(data: dict[str, object]) -> str:
    release = data["release"]
    source = data["source"]
    benchmark = data["benchmark"]
    source_state = (
        "The benchmark and source identities are commit-bound and the evidence tree is clean."
        if source["sourceCommit"] and source["treeState"] == "clean"
        else "The source identity or evidence tree is not yet release-bound."
    )
    release_state = (
        "The preview release evidence is ready and every mandatory gate passes."
        if release["status"] == "ready" and release["complete"]
        else "The release remains fail-closed until its status is ready and every mandatory gate passes."
    )
    return f"""<!-- release-evidence:start -->
| Release evidence | Value |
| --- | --- |
| Version / status | `{release['version']}` / `{release['status']}` |
| Source commit | `{source['sourceCommit'] or 'UNBOUND (dirty draft)'}` |
| CommonMark / cmark | `{benchmark['commonmarkRatio']:.2f}x` / limit `{benchmark['ratioLimit']}x` |
| GFM HTML / cmark-gfm | `{benchmark['gfmRatio']:.2f}x` / limit `{benchmark['ratioLimit']}x` |
| Benchmark identity | `{benchmark['status']}`; commit `{benchmark['sourceCommit'] or 'UNBOUND'}`; SDK `{benchmark['sdkVersion'] or 'UNBOUND'}` |

The table is generated from [`release-evidence.json`](release-evidence.json).
{source_state} {release_state}
<!-- release-evidence:end -->"""


def acceptance_block(data: dict[str, object]) -> str:
    release = data["release"]
    source = data["source"]
    benchmark = data["benchmark"]
    tests = data["tests"]
    source_state = (
        "The benchmark identity is bound and the evidence tree is clean"
        if source["sourceCommit"] and source["treeState"] == "clean"
        else "The benchmark source identity or evidence tree is not release-bound"
    )
    ratios_pass = (
        benchmark["commonmarkRatio"] <= benchmark["ratioLimit"]
        and benchmark["gfmRatio"] <= benchmark["ratioLimit"]
    )
    ready = (
        release["status"] == "ready"
        and release["complete"]
        and source["sourceCommit"]
        and source["treeState"] == "clean"
        and benchmark["status"] == "current"
        and ratios_pass
    )
    conclusion = (
        "All mandatory performance ratios and release-evidence gates pass."
        if ready
        else "One or more mandatory release-evidence gates remain incomplete."
    )
    return f"""<!-- release-evidence:start -->
## Generated Release Evidence

- Version/status: `{release['version']}` / `{release['status']}`.
- Source identity: `{source['sourceCommit'] or 'UNBOUND'}`; tree state `{source['treeState']}`.
- Tests: `{tests['passed']}/{tests['total']}` passed, `{tests['skipped']}` skipped, `{tests['failed']}` failed.
- Benchmark: CommonMark `{benchmark['commonmarkRatio']:.2f}x`, GFM `{benchmark['gfmRatio']:.2f}x`, status `{benchmark['status']}`.
- Raw digest: `{benchmark['rawSha256']}`.

{source_state}. {conclusion}
<!-- release-evidence:end -->"""


def replace_block(path: Path, block: str) -> str:
    text = path.read_text(encoding="utf-8")
    start = "<!-- release-evidence:start -->"
    end = "<!-- release-evidence:end -->"
    if start not in text or end not in text:
        raise ValueError(f"missing release evidence markers in {path.relative_to(ROOT)}")
    prefix, remainder = text.split(start, 1)
    _, suffix = remainder.split(end, 1)
    return prefix + block + suffix


def validate(data: dict[str, object], release_ready: bool) -> list[str]:
    errors: list[str] = []
    for section, path_key, digest_key in (
        (data["conformance"]["commonmark"], "corpusPath", "corpusSha256"),
        (data["conformance"]["gfm"], "corpusPath", "corpusSha256"),
        (data["api"], "snapshotPath", "sha256"),
        (data["benchmark"], "rawPath", "rawSha256"),
    ):
        path = ROOT / section[path_key]
        if not path.exists():
            errors.append(f"missing {path.relative_to(ROOT)}")
        elif digest(path) != section[digest_key]:
            errors.append(f"digest mismatch: {path.relative_to(ROOT)}")
    raw = json.loads((ROOT / data["benchmark"]["rawPath"]).read_text(encoding="utf-8"))
    benchmark = data["benchmark"]
    for name, evidence_key in (
        ("commonmark", "commonmarkRatio"),
        ("gfm", "gfmRatio"),
    ):
        actual = raw[name]["geometricMeanRatio"]
        if abs(actual - benchmark[evidence_key]) > 1.0e-12:
            errors.append(f"benchmark ratio mismatch: {name}")
    if raw["environment"]["cmark"] != benchmark["cmark"]:
        errors.append("cmark identity does not match raw benchmark")
    if raw["environment"]["cmarkGfm"] != benchmark["cmarkGfm"]:
        errors.append("cmark-gfm identity does not match raw benchmark")
    if raw["environment"]["cangjieOptimization"] not in data["toolchain"]["compilerFlags"]:
        errors.append("benchmark optimization is absent from compiler flags")
    for raw_key, evidence_key in (
        ("sourceCommit", "sourceCommit"),
        ("productSourceArchiveSha256", "productSourceArchiveSha256"),
        ("benchmarkHarnessSha256", "benchmarkHarnessSha256"),
        ("markdownDriverSha256", "markdownDriverSha256"),
        ("cmarkDriverSha256", "cmarkDriverSha256"),
        ("cmarkGfmDriverSha256", "cmarkGfmDriverSha256"),
    ):
        if raw.get("identity", {}).get(raw_key) != benchmark.get(evidence_key):
            errors.append(f"benchmark identity mismatch: {raw_key}")
    if raw["environment"].get("cangjieSdkVersion") != benchmark["sdkVersion"]:
        errors.append("benchmark SDK identity does not match raw benchmark")
    failed_raw_gates = sorted(name for name, passed in raw.get("gates", {}).items() if not passed)
    if failed_raw_gates:
        errors.append("canonical benchmark gates failed: " + ", ".join(failed_raw_gates))
    if benchmark["status"] == "current" and benchmark["sourceCommit"] != data["source"]["sourceCommit"]:
        errors.append("current benchmark source does not match release source")
    if release_ready:
        if data["release"]["status"] != "ready" or not data["release"]["complete"]:
            errors.append("release status is not ready/complete")
        if not data["source"]["sourceCommit"] or data["source"]["treeState"] != "clean":
            errors.append("source commit is unbound or tree is not clean")
        if data["benchmark"]["status"] != "current":
            errors.append("benchmark is not current")
        if not data["benchmark"]["sourceCommit"] or not data["benchmark"]["sdkVersion"]:
            errors.append("benchmark source commit or SDK is unbound")
        if (benchmark["commonmarkRatio"] > benchmark["ratioLimit"]
                or benchmark["gfmRatio"] > benchmark["ratioLimit"]):
            errors.append("mandatory benchmark ratio gate failed")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--release-ready", action="store_true")
    args = parser.parse_args()
    data = load()
    expected_readme = replace_block(README, readme_block(data))
    expected_acceptance = replace_block(ACCEPTANCE, acceptance_block(data))
    expected_benchmark = benchmark_markdown(data)
    if args.write:
        README.write_text(expected_readme, encoding="utf-8")
        ACCEPTANCE.write_text(expected_acceptance, encoding="utf-8")
        BENCHMARK_REPORT.write_text(expected_benchmark, encoding="utf-8")
    else:
        if README.read_text(encoding="utf-8") != expected_readme:
            print("README release-evidence block is stale", file=sys.stderr)
            return 1
        if ACCEPTANCE.read_text(encoding="utf-8") != expected_acceptance:
            print("acceptance release-evidence block is stale", file=sys.stderr)
            return 1
        if BENCHMARK_REPORT.read_text(encoding="utf-8") != expected_benchmark:
            print("benchmark report is stale", file=sys.stderr)
            return 1
    errors = validate(data, args.release_ready)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print("release evidence verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
