#!/usr/bin/env python3
"""Validate and render the single release-evidence source of truth."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "benchmarks"))

from benchmark_identity import benchmark_product_tree_sha256
from measure import benchmark_corpora


EVIDENCE = ROOT / "release-evidence.json"
README = ROOT / "README.md"
BENCHMARK_REPORT = ROOT / "docs/reports/benchmark.md"
ACCEPTANCE = ROOT / ".agent/acceptance-report.md"
BENCHMARK_HARNESS = ROOT / "benchmarks/measure.py"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load() -> dict[str, object]:
    return json.loads(EVIDENCE.read_text(encoding="utf-8"))


def benchmark_markdown(data: dict[str, object]) -> str:
    benchmark = data["benchmark"]
    assert isinstance(benchmark, dict)
    ratios_pass = (
        benchmark["commonmarkRatio"] <= benchmark["ratioLimit"]
        and benchmark["gfmRatio"] <= benchmark["ratioLimit"]
    )
    status = "PASS" if benchmark["status"] == "current" and ratios_pass else "FAIL"
    return f"""# Release benchmark report

Status: **{status}**

Evidence status: `{benchmark['status']}`. {benchmark['note']}

- CommonMark parse-only geometric mean ratio vs cmark: `{benchmark['commonmarkRatio']:.2f}x` (limit `{benchmark['ratioLimit']}x`).
- GFM parse+HTML geometric mean ratio vs cmark-gfm: `{benchmark['gfmRatio']:.2f}x` (limit `{benchmark['ratioLimit']}x`).
- Raw report: `{benchmark['rawPath']}`.
- Raw SHA-256: `{benchmark['rawSha256']}`.
- Tested source commit: `{benchmark['sourceCommit'] or 'UNBOUND'}`.
- Benchmark Cangjie SDK: `{benchmark['sdkVersion'] or 'UNBOUND'}`.
- Product source archive SHA-256: `{benchmark['productSourceArchiveSha256']}`.
- Product source tree SHA-256: `{benchmark['productTreeSha256'] or 'UNBOUND'}`.
- Benchmark harness SHA-256: `{benchmark['benchmarkHarnessSha256']}`.
- markdown driver SHA-256: `{benchmark['markdownDriverSha256']}`.
- cmark driver SHA-256: `{benchmark['cmarkDriverSha256']}`.
- cmark-gfm driver SHA-256: `{benchmark['cmarkGfmDriverSha256']}`.
- cmark: `{benchmark['cmark']}`.
- cmark-gfm: `{benchmark['cmarkGfm']}`.

This file is generated by `python3 scripts/release_evidence.py --write` from
`release-evidence.json`; do not edit benchmark numbers here.
"""


def readme_block(data: dict[str, object]) -> str:
    release = data["release"]
    identity = data["identity"]
    benchmark = data["benchmark"]
    evidence_state = "ready" if release["evidenceReady"] else "not ready"
    ci_state = "yes" if release["ciVerifiedAtHead"] else "no"
    publication_state = "yes" if release["published"] else "no"
    return f"""<!-- release-evidence:start -->
| Release evidence | Value |
| --- | --- |
| Version / status | `{release['version']}` / `{release['status']}` |
| Offline evidence ready | `{evidence_state}` |
| CI verified at evidence repository HEAD | `{ci_state}` |
| Published release | `{publication_state}` |
| Artifact commit | `{identity['artifactCommit'] or 'UNBOUND'}` |
| Evidence commit | `{identity['evidenceCommit'] or 'UNBOUND'}` |
| Repository HEAD at generation | `{identity['repositoryHeadAtGeneration'] or 'UNBOUND'}` |
| CommonMark / cmark | `{benchmark['commonmarkRatio']:.2f}x` / limit `{benchmark['ratioLimit']}x` |
| GFM HTML / cmark-gfm | `{benchmark['gfmRatio']:.2f}x` / limit `{benchmark['ratioLimit']}x` |
| Benchmark identity | `{benchmark['status']}`; commit `{benchmark['sourceCommit'] or 'UNBOUND'}`; SDK `{benchmark['sdkVersion'] or 'UNBOUND'}` |

The table is generated from [`release-evidence.json`](release-evidence.json).
`evidenceReady` describes reproducible offline artifacts and gates only. It does not claim that
the current repository HEAD passed hosted CI or that a GitHub release was published.
<!-- release-evidence:end -->"""


def acceptance_block(data: dict[str, object]) -> str:
    release = data["release"]
    identity = data["identity"]
    benchmark = data["benchmark"]
    tests = data["tests"]
    ratios_pass = (
        benchmark["commonmarkRatio"] <= benchmark["ratioLimit"]
        and benchmark["gfmRatio"] <= benchmark["ratioLimit"]
    )
    ready = (
        release["evidenceReady"]
        and identity["artifactCommit"]
        and identity["evidenceCommit"]
        and identity["treeStateAtGeneration"] == "clean"
        and benchmark["status"] == "current"
        and ratios_pass
    )
    conclusion = (
        "All mandatory offline evidence and performance gates pass."
        if ready
        else "One or more mandatory offline evidence gates remain incomplete."
    )
    return f"""<!-- release-evidence:start -->
## Generated Release Evidence

- Version/status: `{release['version']}` / `{release['status']}`.
- Artifact commit: `{identity['artifactCommit'] or 'UNBOUND'}`.
- Evidence commit: `{identity['evidenceCommit'] or 'UNBOUND'}`; repository HEAD at generation `{identity['repositoryHeadAtGeneration'] or 'UNBOUND'}`.
- Hosted CI verified at that HEAD: `{release['ciVerifiedAtHead']}`; published: `{release['published']}`.
- Tests: `{tests['passed']}/{tests['total']}` passed, `{tests['skipped']}` skipped, `{tests['failed']}` failed.
- Benchmark: CommonMark `{benchmark['commonmarkRatio']:.2f}x`, GFM `{benchmark['gfmRatio']:.2f}x`, status `{benchmark['status']}`.
- Raw digest: `{benchmark['rawSha256']}`.

{conclusion} Hosted CI and publication remain separate claims.
<!-- release-evidence:end -->"""


def replace_block(path: Path, block: str) -> str:
    text = path.read_text(encoding="utf-8")
    start = "<!-- release-evidence:start -->"
    end = "<!-- release-evidence:end -->"
    if start not in text or end not in text:
        raise ValueError(f"missing release evidence markers in {path.relative_to(ROOT)}")
    prefix, remainder = text.split(start, 1)
    _, suffix = remainder.split(end, 1)
    return prefix + block + suffix


def validate_current_benchmark_identity(raw: dict[str, object],
        benchmark: dict[str, object]) -> list[str]:
    errors: list[str] = []
    raw_corpora = raw.get("corpora", {})
    assert isinstance(raw_corpora, dict)
    current_corpora = benchmark_corpora()
    if set(raw_corpora) != set(current_corpora):
        errors.append("benchmark corpus inventory does not match current harness")
    for name, content in current_corpora.items():
        recorded = raw_corpora.get(name)
        if not isinstance(recorded, dict):
            errors.append(f"benchmark corpus is missing: {name}")
            continue
        if recorded.get("bytes") != len(content):
            errors.append(f"benchmark corpus byte length mismatch: {name}")
        if recorded.get("sha256") != hashlib.sha256(content).hexdigest():
            errors.append(f"benchmark corpus digest mismatch: {name}")

    current_tree = benchmark_product_tree_sha256(ROOT)
    raw_tree = raw.get("identity", {}).get("productTreeSha256")
    evidence_tree = benchmark.get("productTreeSha256")
    if not raw_tree or raw_tree != evidence_tree:
        errors.append("benchmark product tree identity is unbound or inconsistent")
    if raw_tree != current_tree:
        errors.append("benchmark product tree does not match current sources")

    raw_harness = raw.get("identity", {}).get("benchmarkHarnessSha256")
    evidence_harness = benchmark.get("benchmarkHarnessSha256")
    if not raw_harness or raw_harness != evidence_harness:
        errors.append("benchmark harness identity is unbound or inconsistent")
    if raw_harness != digest(BENCHMARK_HARNESS):
        errors.append("benchmark harness does not match current measure.py")
    return errors


def validate_reachable_commit(commit: object, label: str) -> list[str]:
    if not isinstance(commit, str) or not commit:
        return [f"{label} commit is unbound"]
    inside = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if inside.returncode != 0:
        return []
    reachable = subprocess.run(
        ["git", "merge-base", "--is-ancestor", commit, "HEAD"],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if reachable.returncode != 0:
        return [f"{label} commit is not reachable from repository HEAD: {commit}"]
    return []


def validate(data: dict[str, object], evidence_ready: bool) -> list[str]:
    errors: list[str] = []
    if data.get("schemaVersion") != 3:
        errors.append("release evidence schemaVersion must be 3")
    for section, path_key, digest_key in (
        (data["conformance"]["commonmark"], "corpusPath", "corpusSha256"),
        (data["conformance"]["gfm"], "corpusPath", "corpusSha256"),
        (data["api"], "snapshotPath", "sha256"),
        (data["benchmark"], "rawPath", "rawSha256"),
    ):
        path = ROOT / section[path_key]
        if not path.exists():
            errors.append(f"missing {path.relative_to(ROOT)}")
        elif digest(path) != section[digest_key]:
            errors.append(f"digest mismatch: {path.relative_to(ROOT)}")
    raw = json.loads((ROOT / data["benchmark"]["rawPath"]).read_text(encoding="utf-8"))
    benchmark = data["benchmark"]
    for name, evidence_key in (
        ("commonmark", "commonmarkRatio"),
        ("gfm", "gfmRatio"),
    ):
        actual = raw[name]["geometricMeanRatio"]
        if abs(actual - benchmark[evidence_key]) > 1.0e-12:
            errors.append(f"benchmark ratio mismatch: {name}")
    if raw["environment"]["cmark"] != benchmark["cmark"]:
        errors.append("cmark identity does not match raw benchmark")
    if raw["environment"]["cmarkGfm"] != benchmark["cmarkGfm"]:
        errors.append("cmark-gfm identity does not match raw benchmark")
    if raw["environment"]["cangjieOptimization"] not in data["toolchain"]["compilerFlags"]:
        errors.append("benchmark optimization is absent from compiler flags")
    for raw_key, evidence_key in (
        ("sourceCommit", "sourceCommit"),
        ("productSourceArchiveSha256", "productSourceArchiveSha256"),
        ("benchmarkHarnessSha256", "benchmarkHarnessSha256"),
        ("markdownDriverSha256", "markdownDriverSha256"),
        ("cmarkDriverSha256", "cmarkDriverSha256"),
        ("cmarkGfmDriverSha256", "cmarkGfmDriverSha256"),
    ):
        if raw.get("identity", {}).get(raw_key) != benchmark.get(evidence_key):
            errors.append(f"benchmark identity mismatch: {raw_key}")
    if raw["environment"].get("cangjieSdkVersion") != benchmark["sdkVersion"]:
        errors.append("benchmark SDK identity does not match raw benchmark")
    if benchmark["status"] == "current" or evidence_ready:
        errors.extend(validate_current_benchmark_identity(raw, benchmark))
    failed_raw_gates = sorted(name for name, passed in raw.get("gates", {}).items() if not passed)
    if failed_raw_gates and (evidence_ready or data["release"]["evidenceReady"]):
        errors.append("canonical benchmark gates failed: " + ", ".join(failed_raw_gates))
    identity = data["identity"]
    release = data["release"]
    if benchmark["status"] == "current" or evidence_ready:
        errors.extend(validate_reachable_commit(benchmark["sourceCommit"], "benchmark source"))
        errors.extend(validate_reachable_commit(identity["artifactCommit"], "artifact"))
        errors.extend(validate_reachable_commit(identity["evidenceCommit"], "evidence"))
        errors.extend(validate_reachable_commit(
            identity["repositoryHeadAtGeneration"], "repository generation HEAD"
        ))
    if benchmark["status"] == "current" and benchmark["sourceCommit"] != identity["artifactCommit"]:
        errors.append("current benchmark source does not match artifact commit")
    if release["ciVerifiedAtHead"]:
        if (not release["ciVerifiedCommit"]
                or release["ciVerifiedCommit"] != identity["repositoryHeadAtGeneration"]):
            errors.append("CI verified-at-HEAD claim is not bound to the evidence repository HEAD")
    if release["published"] and not release["ciVerifiedAtHead"]:
        errors.append("published release is not CI-verified at the evidence repository HEAD")
    if evidence_ready:
        if release["status"] != "evidence-ready" or not release["evidenceReady"]:
            errors.append("offline evidence status is not evidence-ready")
        if (not identity["artifactCommit"] or not identity["evidenceCommit"]
                or not identity["repositoryHeadAtGeneration"]
                or identity["treeStateAtGeneration"] != "clean"):
            errors.append("artifact/evidence identity is unbound or generation tree is not clean")
        if data["benchmark"]["status"] != "current":
            errors.append("benchmark is not current")
        if not data["benchmark"]["sourceCommit"] or not data["benchmark"]["sdkVersion"]:
            errors.append("benchmark source commit or SDK is unbound")
        if (benchmark["commonmarkRatio"] > benchmark["ratioLimit"]
                or benchmark["gfmRatio"] > benchmark["ratioLimit"]):
            errors.append("mandatory benchmark ratio gate failed")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--evidence-ready", action="store_true")
    args = parser.parse_args()
    data = load()
    expected_readme = replace_block(README, readme_block(data))
    expected_acceptance = replace_block(ACCEPTANCE, acceptance_block(data))
    expected_benchmark = benchmark_markdown(data)
    if args.write:
        README.write_text(expected_readme, encoding="utf-8")
        ACCEPTANCE.write_text(expected_acceptance, encoding="utf-8")
        BENCHMARK_REPORT.write_text(expected_benchmark, encoding="utf-8")
    else:
        if README.read_text(encoding="utf-8") != expected_readme:
            print("README release-evidence block is stale", file=sys.stderr)
            return 1
        if ACCEPTANCE.read_text(encoding="utf-8") != expected_acceptance:
            print("acceptance release-evidence block is stale", file=sys.stderr)
            return 1
        if BENCHMARK_REPORT.read_text(encoding="utf-8") != expected_benchmark:
            print("benchmark report is stale", file=sys.stderr)
            return 1
    errors = validate(data, args.evidence_ready)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print("release evidence verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
