#!/usr/bin/env python3
"""Validate and render the single release-evidence source of truth."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "benchmarks"))
sys.path.insert(0, str(ROOT / "scripts"))

from benchmark_identity import (
    PRODUCT_FILES,
    PRODUCT_ROOTS,
    benchmark_product_tree_sha256,
)
from measure import benchmark_corpora
from release_statistics import (
    benchmark_harness_sha256,
    validate_benchmark_derivations,
)
from release_evidence_bundle import verify_checksums


EVIDENCE = ROOT / "release-evidence.json"
README = ROOT / "README.md"
CHANGELOG = ROOT / "CHANGELOG.md"
PERFORMANCE = ROOT / "docs/performance.md"
BENCHMARK_REPORT = ROOT / "docs/reports/benchmark.md"
ACCEPTANCE = ROOT / ".agent/acceptance-report.md"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load() -> dict[str, object]:
    return json.loads(EVIDENCE.read_text(encoding="utf-8"))


def benchmark_markdown(data: dict[str, object]) -> str:
    benchmark = data["benchmark"]
    assert isinstance(benchmark, dict)
    ratios_pass = (
        benchmark["commonmarkRatio"] <= benchmark["ratioLimit"]
        and benchmark["gfmRatio"] <= benchmark["ratioLimit"]
    )
    status = "PASS" if benchmark["status"] == "current" and ratios_pass else "FAIL"
    return f"""# Release benchmark report

Status: **{status}**

Evidence status: `{benchmark['status']}`. {benchmark['note']}

- CommonMark parse-only geometric mean ratio vs cmark: `{benchmark['commonmarkRatio']:.2f}x` (limit `{benchmark['ratioLimit']}x`).
- GFM parse+HTML geometric mean ratio vs cmark-gfm: `{benchmark['gfmRatio']:.2f}x` (limit `{benchmark['ratioLimit']}x`).
- Raw report: `{benchmark['rawPath']}`.
- Raw SHA-256: `{benchmark['rawSha256']}`.
- Tested source commit: `{benchmark['sourceCommit'] or 'UNBOUND'}`.
- Tested source Git tree: `{benchmark.get('sourceGitTree') or 'UNBOUND'}`.
- Benchmark Cangjie SDK: `{benchmark['sdkVersion'] or 'UNBOUND'}`.
- Product source archive SHA-256: `{benchmark['productSourceArchiveSha256']}`.
- Product source tree SHA-256: `{benchmark['productTreeSha256'] or 'UNBOUND'}`.
- Benchmark harness SHA-256: `{benchmark['benchmarkHarnessSha256']}`.
- markdown driver SHA-256: `{benchmark['markdownDriverSha256']}`.
- cmark driver SHA-256: `{benchmark['cmarkDriverSha256']}`.
- cmark-gfm driver SHA-256: `{benchmark['cmarkGfmDriverSha256']}`.
- cmark: `{benchmark['cmark']}`.
- cmark-gfm: `{benchmark['cmarkGfm']}`.

This file is generated by `python3 scripts/release_evidence.py --write` from
`release-evidence.json`; do not edit benchmark numbers here.
"""


def readme_block(data: dict[str, object]) -> str:
    release = data["release"]
    identity = data["identity"]
    benchmark = data["benchmark"]
    tests = data["tests"]
    api = data["api"]
    conformance = data["conformance"]
    evidence_state = "ready" if release["evidenceReady"] else "not ready"
    ci_state = "yes" if release["ciVerifiedAtHead"] else "no"
    publication_state = "yes" if release["published"] else "no"
    return f"""`release-evidence.json` 是当前测试、规范和 benchmark 数字的唯一事实源。

<!-- release-evidence:start -->
| Release evidence | Value |
| --- | --- |
| Version / status | `{release['version']}` / `{release['status']}` |
| Offline evidence ready | `{evidence_state}` |
| CI verified at evidence repository HEAD | `{ci_state}` |
| Published release | `{publication_state}` |
| Tests | `{tests['passed']}/{tests['total']}` passed; `{tests['skipped']}` skipped; `{tests['failed']}` failed |
| CommonMark conformance | `{conformance['commonmark']['passed']}/{conformance['commonmark']['total']}` |
| GFM conformance | `{conformance['gfm']['passed']}/{conformance['gfm']['total']}` |
| Public API snapshot | `{api['declarations']}` declarations |
| Artifact commit | `{identity['artifactCommit'] or 'UNBOUND'}` |
| Evidence subject commit | `{identity['evidenceCommit'] or 'UNBOUND'}` |
| Execution identity | `target/release-evidence/manifest.json` records and verifies the clean gate commit/tree |
| CommonMark / cmark | `{benchmark['commonmarkRatio']:.2f}x` / limit `{benchmark['ratioLimit']}x` |
| GFM HTML / cmark-gfm | `{benchmark['gfmRatio']:.2f}x` / limit `{benchmark['ratioLimit']}x` |
| Benchmark identity | `{benchmark['status']}`; commit `{benchmark['sourceCommit'] or 'UNBOUND'}`; SDK `{benchmark['sdkVersion'] or 'UNBOUND'}` |

The table is generated from [`release-evidence.json`](release-evidence.json).
`evidenceReady` describes reproducible offline artifacts and gates only. It does not claim that
the current repository HEAD passed hosted CI or that a GitHub release was published.
<!-- release-evidence:end -->"""


def changelog_block(data: dict[str, object]) -> str:
    benchmark = data["benchmark"]
    tests = data["tests"]
    api = data["api"]
    conformance = data["conformance"]
    benchmark_label = "canonical" if benchmark["status"] == "current" else "last complete"
    return f"""<!-- release-evidence:start -->
当前数字只由 [`release-evidence.json`](release-evidence.json)提供：

- benchmark evidence status `{benchmark['status']}`；
- CommonMark `{conformance['commonmark']['passed']}/{conformance['commonmark']['total']}`；
- GFM `{conformance['gfm']['passed']}/{conformance['gfm']['total']}`；
- 测试 `{tests['passed']}/{tests['total']}`，`{tests['skipped']}` skipped，`{tests['failed']}` failed；
- public API snapshot `{api['declarations']}` declarations；
- {benchmark_label} CommonMark ratio `{benchmark['commonmarkRatio']:.6f}x`；
- {benchmark_label} GFM ratio `{benchmark['gfmRatio']:.6f}x`。

原始数据和受测 commit identity 见 `docs/reports/benchmark-raw.json`。
<!-- release-evidence:end -->"""


def performance_block(data: dict[str, object]) -> str:
    benchmark = data["benchmark"]
    if benchmark["status"] != "current":
        commonmark_status = "stale"
        gfm_status = "stale"
    else:
        commonmark_status = (
            "pass" if benchmark["commonmarkRatio"] <= benchmark["ratioLimit"] else "fail"
        )
        gfm_status = "pass" if benchmark["gfmRatio"] <= benchmark["ratioLimit"] else "fail"
    return f"""<!-- release-evidence:start -->
当前 release benchmark 使用固定 Server CPU、Cangjie SDK
`{benchmark['sdkVersion']}` 和 release 构建。

| Profile | 对比对象 | 当前 ratio | 门槛 | 状态 |
| --- | --- | ---: | ---: | --- |
| CommonMark 完整 AST parse | cmark 0.31.1 | `{benchmark['commonmarkRatio']:.6f}x` | `≤{benchmark['ratioLimit']}x` | {commonmark_status} |
| GFM 完整 AST + HTML | cmark-gfm 0.29 | `{benchmark['gfmRatio']:.6f}x` | `≤{benchmark['ratioLimit']}x` | {gfm_status} |

ratio 大于 1 表示本库更慢。完整语料、样本、RSS、复杂度和 identity 见
[canonical report](reports/benchmark.md)与其链接的 raw JSON。
<!-- release-evidence:end -->"""


def acceptance_block(data: dict[str, object]) -> str:
    release = data["release"]
    identity = data["identity"]
    benchmark = data["benchmark"]
    tests = data["tests"]
    ratios_pass = (
        benchmark["commonmarkRatio"] <= benchmark["ratioLimit"]
        and benchmark["gfmRatio"] <= benchmark["ratioLimit"]
    )
    ready = (
        release["evidenceReady"]
        and identity["artifactCommit"]
        and identity["evidenceCommit"]
        and benchmark["status"] == "current"
        and ratios_pass
    )
    conclusion = (
        "All mandatory offline evidence and performance gates pass."
        if ready
        else "One or more mandatory offline evidence gates remain incomplete."
    )
    return f"""<!-- release-evidence:start -->
## Generated Release Evidence

- Version/status: `{release['version']}` / `{release['status']}`.
- Artifact commit: `{identity['artifactCommit'] or 'UNBOUND'}`.
- Evidence subject commit: `{identity['evidenceCommit'] or 'UNBOUND'}`; the retained execution manifest binds the clean gate commit and Git tree.
- Hosted CI verified at that HEAD: `{release['ciVerifiedAtHead']}`; published: `{release['published']}`.
- Tests: `{tests['passed']}/{tests['total']}` passed, `{tests['skipped']}` skipped, `{tests['failed']}` failed.
- Benchmark: CommonMark `{benchmark['commonmarkRatio']:.2f}x`, GFM `{benchmark['gfmRatio']:.2f}x`, status `{benchmark['status']}`.
- Raw digest: `{benchmark['rawSha256']}`.

{conclusion} Hosted CI and publication remain separate claims.
<!-- release-evidence:end -->"""


def replace_block(path: Path, block: str) -> str:
    text = path.read_text(encoding="utf-8")
    start = "<!-- release-evidence:start -->"
    end = "<!-- release-evidence:end -->"
    if start not in text or end not in text:
        raise ValueError(f"missing release evidence markers in {path.relative_to(ROOT)}")
    prefix, remainder = text.split(start, 1)
    _, suffix = remainder.split(end, 1)
    return prefix + block + suffix


def replace_section(path: Path, heading: str, next_heading: str, body: str) -> str:
    """Replace one complete Markdown section so facts cannot drift outside markers."""
    text = path.read_text(encoding="utf-8")
    start_marker = heading + "\n"
    end_marker = next_heading + "\n"
    if text.count(start_marker) != 1:
        raise ValueError(
            f"expected exactly one {heading!r} section in {path.relative_to(ROOT)}"
        )
    prefix, remainder = text.split(start_marker, 1)
    if remainder.count(end_marker) != 1:
        raise ValueError(
            f"expected exactly one {next_heading!r} boundary in {path.relative_to(ROOT)}"
        )
    _, suffix = remainder.split(end_marker, 1)
    return (
        prefix + start_marker + "\n" + body.rstrip() + "\n\n"
        + end_marker + suffix
    )


def validate_current_benchmark_identity(raw: dict[str, object],
        benchmark: dict[str, object]) -> list[str]:
    errors: list[str] = []
    raw_corpora = raw.get("corpora", {})
    assert isinstance(raw_corpora, dict)
    current_corpora = benchmark_corpora()
    if set(raw_corpora) != set(current_corpora):
        errors.append("benchmark corpus inventory does not match current harness")
    for name, content in current_corpora.items():
        recorded = raw_corpora.get(name)
        if not isinstance(recorded, dict):
            errors.append(f"benchmark corpus is missing: {name}")
            continue
        if recorded.get("bytes") != len(content):
            errors.append(f"benchmark corpus byte length mismatch: {name}")
        if recorded.get("sha256") != hashlib.sha256(content).hexdigest():
            errors.append(f"benchmark corpus digest mismatch: {name}")

    current_tree = benchmark_product_tree_sha256(ROOT)
    raw_tree = raw.get("identity", {}).get("productTreeSha256")
    evidence_tree = benchmark.get("productTreeSha256")
    if not raw_tree or raw_tree != evidence_tree:
        errors.append("benchmark product tree identity is unbound or inconsistent")
    if raw_tree != current_tree:
        errors.append("benchmark product tree does not match current sources")

    raw_harness = raw.get("identity", {}).get("benchmarkHarnessSha256")
    evidence_harness = benchmark.get("benchmarkHarnessSha256")
    if not raw_harness or raw_harness != evidence_harness:
        errors.append("benchmark harness identity is unbound or inconsistent")
    if raw_harness != benchmark_harness_sha256(ROOT):
        errors.append("benchmark harness does not match current harness files")
    errors.extend(validate_benchmark_derivations(raw))
    return errors


def validate_reachable_commit(commit: object, label: str) -> list[str]:
    if not isinstance(commit, str) or not commit:
        return [f"{label} commit is unbound"]
    inside = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if inside.returncode != 0:
        return [f"{label} commit cannot be verified outside a Git work tree"]
    reachable = subprocess.run(
        ["git", "merge-base", "--is-ancestor", commit, "HEAD"],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if reachable.returncode != 0:
        return [f"{label} commit is not reachable from repository HEAD: {commit}"]
    return []


def benchmark_product_tree_sha256_at_commit(commit: str, root: Path | None = None) -> str:
    """Compute the benchmark product tree from Git blobs, never the work tree."""
    if root is None:
        root = ROOT
    listing = subprocess.run(
        ["git", "ls-tree", "-rz", "--name-only", commit, "--", *PRODUCT_FILES,
         *PRODUCT_ROOTS],
        cwd=root,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if listing.returncode != 0:
        raise ValueError(listing.stderr.decode("utf-8", errors="replace").strip())
    paths = sorted(
        path.decode("utf-8")
        for path in listing.stdout.split(b"\0")
        if path
    )
    digest_value = hashlib.sha256(b"markdown-benchmark-product-tree-v1\0")
    for path in paths:
        blob = subprocess.run(
            ["git", "show", f"{commit}:{path}"],
            cwd=root,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if blob.returncode != 0:
            raise ValueError(blob.stderr.decode("utf-8", errors="replace").strip())
        encoded = path.encode("utf-8")
        digest_value.update(len(encoded).to_bytes(8, "big"))
        digest_value.update(encoded)
        digest_value.update(len(blob.stdout).to_bytes(8, "big"))
        digest_value.update(blob.stdout)
    return digest_value.hexdigest()


def validate_commit_product_tree(commit: object, label: str,
        expected_tree: object) -> list[str]:
    errors = validate_reachable_commit(commit, label)
    if errors:
        return errors
    if not isinstance(expected_tree, str) or not expected_tree:
        return [f"{label} product tree is unbound"]
    assert isinstance(commit, str)
    try:
        actual_tree = benchmark_product_tree_sha256_at_commit(commit)
    except ValueError as error:
        return [f"{label} product tree cannot be read from commit {commit}: {error}"]
    if actual_tree != expected_tree:
        return [f"{label} commit product tree does not match benchmark identity: {commit}"]
    return []


def validate_commit_git_tree(commit: object, label: str, expected_tree: object) -> list[str]:
    if not isinstance(commit, str) or not commit:
        return [f"{label} commit is unbound"]
    if not isinstance(expected_tree, str) or not expected_tree:
        return [f"{label} Git tree is unbound"]
    result = subprocess.run(
        ["git", "rev-parse", f"{commit}^{{tree}}"], cwd=ROOT, text=True,
        capture_output=True, check=False,
    )
    if result.returncode != 0:
        return [f"{label} Git tree cannot be read from commit: {commit}"]
    if result.stdout.strip() != expected_tree:
        return [f"{label} Git tree does not match commit: {commit}"]
    return []


def validate_sdk_archive_identity(manifest: dict[str, object]) -> list[str]:
    toolchain = manifest.get("toolchain")
    if not isinstance(toolchain, dict):
        return ["release execution manifest has no toolchain identity"]
    archive_digest = toolchain.get("sdkArchiveSha256")
    if (not isinstance(archive_digest, str)
            or re.fullmatch(r"[0-9a-f]{64}", archive_digest) is None):
        return ["release execution manifest has no valid SDK archive SHA-256"]
    return []


def validate_execution_repository_identity(manifest: dict[str, object]) -> list[str]:
    """Bind execution evidence to a real commit with the current exact tree.

    GitButler may place a synthetic workspace commit at HEAD.  An explicitly
    selected publishable branch tip is acceptable only when it is reachable and
    its complete Git tree is byte-identical to the checked-out workspace tree.
    """
    errors: list[str] = []
    commit = manifest.get("repositoryCommit")
    tree = manifest.get("gitTree")
    errors.extend(validate_reachable_commit(commit, "release execution"))
    errors.extend(validate_commit_git_tree(commit, "release execution", tree))
    inside = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"], cwd=ROOT,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False,
    )
    if inside.returncode != 0:
        errors.append("release execution identity cannot be verified outside a Git work tree")
        return errors
    current_tree = subprocess.run(
        ["git", "rev-parse", "HEAD^{tree}"], cwd=ROOT, text=True,
        capture_output=True, check=False,
    ).stdout.strip()
    if current_tree != tree:
        errors.append("release execution Git tree does not match current repository tree")
    selected = os.environ.get("MARKDOWN_RELEASE_COMMIT")
    if selected:
        result = subprocess.run(
            ["git", "rev-parse", f"{selected}^{{commit}}"], cwd=ROOT, text=True,
            capture_output=True, check=False,
        )
        if result.returncode != 0:
            errors.append("MARKDOWN_RELEASE_COMMIT cannot be resolved")
        elif result.stdout.strip() != commit:
            errors.append("release execution commit does not match MARKDOWN_RELEASE_COMMIT")
    return errors


def validate_execution_manifest(data: dict[str, object], path: Path) -> list[str]:
    errors: list[str] = []
    if not path.is_file():
        return [f"release execution manifest is missing: {path}"]
    manifest = json.loads(path.read_text(encoding="utf-8"))
    if manifest.get("schemaVersion") != 1:
        errors.append("release execution manifest schemaVersion must be 1")
    if manifest.get("gateExitCode") != 0:
        errors.append("release execution manifest records a failed gate")
    errors.extend(validate_sdk_archive_identity(manifest))
    steps = manifest.get("steps")
    required_steps = {
        "format", "docs", "native-build-tests", "api-checker-tests", "api",
        "static-check", "release-evidence-consistency", "release-evidence-bundle-tests",
        "release-evidence-tests",
        "benchmark-driver-tests", "build", "native-build", "benchmark-driver",
        "native-fuzz", "benchmark-profile-tests", "tests", "cli-build", "cli-smoke",
        "quickstart", "cookbook", "differential-setup", "differential",
        "benchmark-smoke", "bundle",
    }
    if not isinstance(steps, list):
        errors.append("release execution manifest has no step records")
        steps = []
    names = {step.get("name") for step in steps if isinstance(step, dict)}
    missing = sorted(required_steps - names)
    if missing:
        errors.append("release execution manifest is missing steps: " + ", ".join(missing))
    failed = sorted(
        str(step.get("name")) for step in steps
        if isinstance(step, dict) and step.get("exitCode") != 0
    )
    if failed:
        errors.append("release execution steps failed: " + ", ".join(failed))

    identity = data["identity"]
    benchmark = data["benchmark"]
    errors.extend(validate_execution_repository_identity(manifest))
    if manifest.get("productTreeSha256") != benchmark["productTreeSha256"]:
        errors.append("release execution product tree does not match benchmark identity")
    if manifest.get("treeState") != "clean":
        errors.append("release execution work tree was not clean")

    actual_tests = manifest.get("tests")
    declared_tests = data["tests"]
    if not isinstance(actual_tests, dict):
        errors.append("release execution JUnit metrics are missing")
    else:
        expected_tests = {
            "total": declared_tests["total"],
            "passed": declared_tests["passed"],
            "skipped": declared_tests["skipped"],
            "failures": declared_tests["failed"],
            "errors": declared_tests["errors"],
        }
        if actual_tests != expected_tests:
            errors.append("declared test metrics do not match JUnit XML")
        if (actual_tests.get("failures") != 0 or actual_tests.get("errors") != 0
                or actual_tests.get("passed", 0) + actual_tests.get("skipped", 0)
                != actual_tests.get("total")):
            errors.append("JUnit XML does not prove a complete passing test run")

    conformance = manifest.get("conformance", {})
    for key in ("commonmark", "gfm"):
        actual = conformance.get(key) if isinstance(conformance, dict) else None
        declared = data["conformance"][key]
        if (not isinstance(actual, dict) or actual.get("passed") != declared["passed"]
                or actual.get("total") != declared["total"]
                or actual.get("failures") != 0 or actual.get("errors") != 0):
            errors.append(f"declared {key} conformance metrics do not match JUnit XML")

    actual_api = manifest.get("api")
    if (not isinstance(actual_api, dict)
            or actual_api.get("declarations") != data["api"]["declarations"]
            or actual_api.get("snapshotSha256") != data["api"]["sha256"]):
        errors.append("declared API metrics do not match the generated inventory")
    actual_benchmark = manifest.get("benchmark")
    if (not isinstance(actual_benchmark, dict)
            or actual_benchmark.get("rawSha256") != benchmark["rawSha256"]
            or actual_benchmark.get("derivationErrors") != []):
        errors.append("release execution benchmark samples do not prove declared statistics")
    errors.extend(verify_checksums(path.parent))
    return errors


def validate(data: dict[str, object], evidence_ready: bool,
        execution_manifest: Path | None = None) -> list[str]:
    errors: list[str] = []
    if data.get("schemaVersion") not in (3, 4):
        errors.append("release evidence schemaVersion must be 3 or 4")
    for section, path_key, digest_key in (
        (data["conformance"]["commonmark"], "corpusPath", "corpusSha256"),
        (data["conformance"]["gfm"], "corpusPath", "corpusSha256"),
        (data["api"], "snapshotPath", "sha256"),
        (data["benchmark"], "rawPath", "rawSha256"),
    ):
        path = ROOT / section[path_key]
        if not path.exists():
            errors.append(f"missing {path.relative_to(ROOT)}")
        elif digest(path) != section[digest_key]:
            errors.append(f"digest mismatch: {path.relative_to(ROOT)}")
    raw = json.loads((ROOT / data["benchmark"]["rawPath"]).read_text(encoding="utf-8"))
    benchmark = data["benchmark"]
    for name, evidence_key in (
        ("commonmark", "commonmarkRatio"),
        ("gfm", "gfmRatio"),
    ):
        actual = raw[name]["geometricMeanRatio"]
        if abs(actual - benchmark[evidence_key]) > 1.0e-12:
            errors.append(f"benchmark ratio mismatch: {name}")
    if raw["environment"]["cmark"] != benchmark["cmark"]:
        errors.append("cmark identity does not match raw benchmark")
    if raw["environment"]["cmarkGfm"] != benchmark["cmarkGfm"]:
        errors.append("cmark-gfm identity does not match raw benchmark")
    if raw["environment"]["cangjieOptimization"] not in data["toolchain"]["compilerFlags"]:
        errors.append("benchmark optimization is absent from compiler flags")
    for raw_key, evidence_key in (
        ("sourceCommit", "sourceCommit"),
        ("sourceGitTree", "sourceGitTree"),
        ("productSourceArchiveSha256", "productSourceArchiveSha256"),
        ("benchmarkHarnessSha256", "benchmarkHarnessSha256"),
        ("markdownDriverSha256", "markdownDriverSha256"),
        ("cmarkDriverSha256", "cmarkDriverSha256"),
        ("cmarkGfmDriverSha256", "cmarkGfmDriverSha256"),
    ):
        if raw.get("identity", {}).get(raw_key) != benchmark.get(evidence_key):
            errors.append(f"benchmark identity mismatch: {raw_key}")
    if raw["environment"].get("cangjieSdkVersion") != benchmark["sdkVersion"]:
        errors.append("benchmark SDK identity does not match raw benchmark")
    if benchmark["status"] == "current" or evidence_ready:
        errors.extend(validate_current_benchmark_identity(raw, benchmark))
    failed_raw_gates = sorted(name for name, passed in raw.get("gates", {}).items() if not passed)
    if failed_raw_gates and (evidence_ready or data["release"]["evidenceReady"]):
        errors.append("canonical benchmark gates failed: " + ", ".join(failed_raw_gates))
    identity = data["identity"]
    release = data["release"]
    if benchmark["status"] == "current" or evidence_ready:
        expected_tree = benchmark["productTreeSha256"]
        errors.extend(validate_commit_product_tree(
            benchmark["sourceCommit"], "benchmark source", expected_tree
        ))
        errors.extend(validate_commit_product_tree(
            identity["artifactCommit"], "artifact", expected_tree
        ))
        errors.extend(validate_commit_product_tree(
            identity["evidenceCommit"], "evidence", expected_tree
        ))
        errors.extend(validate_commit_git_tree(
            benchmark["sourceCommit"], "benchmark source", benchmark.get("sourceGitTree")
        ))
        if data.get("schemaVersion") == 3:
            errors.extend(validate_commit_product_tree(
                identity["repositoryHeadAtGeneration"], "repository generation HEAD", expected_tree
            ))
    if benchmark["status"] == "current" and benchmark["sourceCommit"] != identity["artifactCommit"]:
        errors.append("current benchmark source does not match artifact commit")
    if release["ciVerifiedAtHead"]:
        if not release["ciVerifiedCommit"]:
            errors.append("CI verified-at-HEAD claim has no commit identity")
    if release["published"] and not release["ciVerifiedAtHead"]:
        errors.append("published release is not CI-verified at the evidence repository HEAD")
    if evidence_ready:
        if data.get("schemaVersion") != 4:
            errors.append("evidence-ready validation requires release evidence schemaVersion 4")
        if release["status"] != "evidence-ready" or not release["evidenceReady"]:
            errors.append("offline evidence status is not evidence-ready")
        if not identity["artifactCommit"] or not identity["evidenceCommit"]:
            errors.append("artifact/evidence subject identity is unbound")
        if data["benchmark"]["status"] != "current":
            errors.append("benchmark is not current")
        if not data["benchmark"]["sourceCommit"] or not data["benchmark"]["sdkVersion"]:
            errors.append("benchmark source commit or SDK is unbound")
        if (benchmark["commonmarkRatio"] > benchmark["ratioLimit"]
                or benchmark["gfmRatio"] > benchmark["ratioLimit"]):
            errors.append("mandatory benchmark ratio gate failed")
        if execution_manifest is None:
            errors.append("evidence-ready validation requires an execution manifest")
        else:
            errors.extend(validate_execution_manifest(data, execution_manifest))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--evidence-ready", action="store_true")
    parser.add_argument("--execution-manifest", type=Path)
    args = parser.parse_args()
    data = load()
    expected_readme = replace_section(
        README, "## 验证状态", "## 参与项目", readme_block(data)
    )
    expected_changelog = replace_section(
        CHANGELOG, "### Evidence", "## 0.8.0 - 2026-08-25", changelog_block(data)
    )
    expected_performance = replace_section(
        PERFORMANCE, "## 当前 canonical 结果", "## 比较了什么", performance_block(data)
    )
    expected_acceptance = replace_block(ACCEPTANCE, acceptance_block(data))
    expected_benchmark = benchmark_markdown(data)
    if args.write:
        README.write_text(expected_readme, encoding="utf-8")
        CHANGELOG.write_text(expected_changelog, encoding="utf-8")
        PERFORMANCE.write_text(expected_performance, encoding="utf-8")
        ACCEPTANCE.write_text(expected_acceptance, encoding="utf-8")
        BENCHMARK_REPORT.write_text(expected_benchmark, encoding="utf-8")
    else:
        if README.read_text(encoding="utf-8") != expected_readme:
            print("README release-evidence section is stale", file=sys.stderr)
            return 1
        if CHANGELOG.read_text(encoding="utf-8") != expected_changelog:
            print("CHANGELOG release-evidence section is stale", file=sys.stderr)
            return 1
        if PERFORMANCE.read_text(encoding="utf-8") != expected_performance:
            print("performance release-evidence section is stale", file=sys.stderr)
            return 1
        if ACCEPTANCE.read_text(encoding="utf-8") != expected_acceptance:
            print("acceptance release-evidence block is stale", file=sys.stderr)
            return 1
        if BENCHMARK_REPORT.read_text(encoding="utf-8") != expected_benchmark:
            print("benchmark report is stale", file=sys.stderr)
            return 1
    errors = validate(data, args.evidence_ready, args.execution_manifest)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print("release evidence verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
