[package]
  cjc-version = "1.1.0"
  name = "markdown_quickstart"
  organization = ""
  description = "markdown public API quickstart"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "executable"
  compile-option = "-O2"
  override-compile-option = ""
  link-option = "-L ../../target/native -lmarkdown_scanner"
  package-configuration = {}

[dependencies]
  "markdown" = { path = "../..", output-type = "static" }
